import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    const val com_github_spotbugs_gradle_plugin: String =
            "com.github.spotbugs:com.github.spotbugs.gradle.plugin:" +
            Versions.com_github_spotbugs_gradle_plugin

    /**
     * https://github.com/pinterest/ktlint */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * https://github.com/uchuhimo/konf */
    const val konf: String = "com.uchuhimo:konf:" + Versions.konf

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * http://www.github.com/kotlintest/kotlintest */
    const val kotlintest_runner_junit5: String = "io.kotlintest:kotlintest-runner-junit5:" +
            Versions.kotlintest_runner_junit5

    /**
     * http://mockk.io */
    const val mockk: String = "io.mockk:mockk:" + Versions.mockk

    const val moquette_broker: String = "io.moquette:moquette-broker:" + Versions.moquette_broker

    const val org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin: String =
            "org.danilopianini.git-sensitive-semantic-versioning:org.danilopianini.git-sensitive-semantic-versioning.gradle.plugin:" +
            Versions.org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin

    /**
     * http://www.eclipse.org/paho */
    const val org_eclipse_paho_client_mqttv3: String =
            "org.eclipse.paho:org.eclipse.paho.client.mqttv3:" +
            Versions.org_eclipse_paho_client_mqttv3

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/ */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * http://www.jgrapht.org */
    const val jgrapht_core: String = "org.jgrapht:jgrapht-core:" + Versions.jgrapht_core

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:" +
            Versions.org_jlleitschuh_gradle_ktlint_gradle_plugin

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://github.com/mockito/mockito */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    /**
     * https://github.com/mockito/mockito */
    const val mockito_junit_jupiter: String = "org.mockito:mockito-junit-jupiter:" +
            Versions.mockito_junit_jupiter

    /**
     * http://www.protelis.org */
    const val protelis: String = "org.protelis:protelis:" + Versions.protelis

    const val slf4j_simple: String = "org.slf4j:slf4j-simple:" + Versions.slf4j_simple
}
