import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * https://github.com/uchuhimo/konf */
    const val konf: String = "com.uchuhimo:konf:_"

    const val moquette_broker: String = "io.moquette:moquette-broker:_"

    /**
     * http://www.eclipse.org/paho */
    const val org_eclipse_paho_client_mqttv3: String = "org.eclipse.paho:org.eclipse.paho.client.mqttv3:_"

    /**
     * http://www.jgrapht.org */
    const val jgrapht_core: String = "org.jgrapht:jgrapht-core:_"

}
